# Python Essential

To start this course, we will do a series of short exercises to refamiliarise ourself with the Python language. We are going to redo in fast pace what we did in the introduction class.

We are going start with the Jupyter Notebook, as we did in the previous class to remind us the python basics and to introduce some new concepts and python commands.

As we mention in the previous class, the best way to learn how to program is to do something meaningful. Last time we learned some fundamental concept in programing by doing some scientific data analysis using the python language. This time we will extend that analysis by transforming it in a proper python software that you can eventually reuse for further study.

## The basics

We learned the concept of *variable* and how to *assign* a value:

In [1]:
dt = 3

And we can verify that the variable has the value *3* as expected:

In [2]:
print('variable "dt" has the value:', dt)

variable "dt" has the value: 3


You can assign to a variable any valid python object: an integer, a float, a string

In [3]:
i = 0
a = 1.1
car = 'aeiou'

print('i =', i, 'is is integer', type(i))
print('a =', a, 'is a float', type(a))
print('car =', car, 'is a string', type(car))

i = 0 is is integer <class 'int'>
a = 1.1 is a float <class 'float'>
car = aeiou is a string <class 'str'>


but it is possible to assign more complex object. Here we are assigning a list. One of the python built-in type:

In [4]:
odds = [1, 3, 4, 5]

It is possible to add element in a list with the method *append* or by using the operator *+*

In [5]:
odds.append(7)
print(odds)

odds = odds + [9]
print(odds)

[1, 3, 4, 5, 7]
[1, 3, 4, 5, 7, 9]


**note**:

You can only use the operator *+* with two lists. Python will return an error if not.

In [6]:
odds + 11

TypeError: can only concatenate list (not "int") to list

But you can concatenate two lists:

In [7]:
odds + [11]

[1, 3, 4, 5, 7, 9, 11]

Python is providing a reverse method for list object:

In [8]:
print('Odds in normal order', odds)
odds.reverse()
print('Odds in reversed order', odds)

Odds in normal order [1, 3, 4, 5, 7, 9]
Odds in reversed order [9, 7, 5, 4, 3, 1]


and a *sort* method: 

In [9]:
a_list = [4, 1, 5, 7]
a_list.sort()
print(a_list)

[1, 4, 5, 7]


** note:**

A list can be a composite object i.e. an object which contains differents type of object *but* the sort method could not work

In [10]:
a_list = [4, 1, 5, 7, 'a', 'z']
print(a_list)


a_list.sort()

[4, 1, 5, 7, 'a', 'z']


TypeError: '<' not supported between instances of 'str' and 'int'

List is a very important object in python and it is very commonly use when you want to realise the same operation by iterating. List can be combined with the *for* loop command to do it. 

## Repeating Actions with loops

One of the main important structure in software development is the loop. Computer are very good at repeating actions and software are build around with capacity. 

Repeating action in Python can be done with two differents structures:

### For Loop

```python

for item in <group>:
    <do something with item>
    <do something>
#end of the loop
```

for each thing in this group, do these operations

In [11]:
for number in [1, 8, 6]:
    print(number)

1
8
6


This is equivalent to:

In [12]:
print(1)
print(8)
print(6)

1
8
6


In [13]:
a_list = [1, 8, 6]
print(a_list[0])
print(a_list[1])
print(a_list[2])


1
8
6


<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>

 <ol>
 <li> 
 Write two different for-loop to print each character in the word ```Mercury```.
 </li>
 <br>
</div>

#### Method 1

In [14]:
word = 'Mercury'
 
for c in word:
    print(c)

M
e
r
c
u
r
y


#### Method 2

In [15]:
word = 'Mercury'
for i in range(len(word)):
    print(word[i])

M
e
r
c
u
r
y


<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>

 <ol>
 <li>
 Create a list which contains the odds numbers &lt; 20.
 </li>
 Hint: You can use the function ```range```.
 <br>
 <li> 
 Can you use another object which is not built-in object in Python similar to the list for numerical object essentially?
 </li>
 Hint: Python capacity can be extended by importing libraries. Here you can use the library ```numpy```.
 <br>
<li>
 Print on screen the 10 digits.
 </li>
 <br>
 
</div>


### Solution challenge 1

In [16]:
odds = list(range(1, 20, 2))
print(odds)
print(type(odds))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
<class 'list'>


## Note: 

In Python 3 the *range* function does not return a list but an iterator to improve the efficiency in term of speed and memory. To create the list you have to force it and use the function *list*.



In [17]:
print('range only:', range(1, 10, 2))

l = list(range(1, 10, 2))
print('range and list:', l)

range only: range(1, 10, 2)
range and list: [1, 3, 5, 7, 9]


### Solution Challenge 2

In [18]:
import numpy as np
odds = np.arange(1,20,2)
print(odds)
print('type is:', type(odds))

[ 1  3  5  7  9 11 13 15 17 19]
type is: <class 'numpy.ndarray'>


### Solution Challenge 3

In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### A new type of loop: *while*

While loop are similar to the  *for* loop since it is made to repeat sections of code. It will not run for a predetermined number of times but until a certain condition is not fulfilled.

This new loop has the following syntax:
```python

while <condition>:
    # instruction 1
    # instruction 2
    # ...
    # instruction N
```

In [20]:
word = 'Mercury'
i = 0
while i < len(word): 
    print(word[i])
    i+=1

M
e
r
c
u
r
y


### *break* keyword

<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>

 <ol>
 <li> Can you explain what will happen with the following piece code?
 </li>
<br>
</div>

```python
while 1: # 1 is always true -> infinite loop
    letter = input("Print 'Q' to exit  : ")
    if letter == "Q":
        print("End of the loop")
```

In [21]:
while 1: # 1 is always true -> infinite loop
    letter = input("Print 'Q' to exit  : ")
    if letter == "Q":
        print("End of the loop")

Print 'Q' to exit  : Q
End of the loop


KeyboardInterrupt: 

To avoid the infinite loop, we can use the keywords *break* to force the software to go out of the loop.


```python
while 1: # 1 is always true -> infinite loop
    letter = input("Print 'Q' to exit  : ")
    if letter == "Q":
        print("End of the loop")
        break
```

In [22]:
while 1: # 1 is always true -> infinite loop
    lettre = input("Print 'Q' to exit  : ")
    if lettre == "Q":
        print("End of the loop")
        break

Print 'Q' to exit  : Q
End of the loop


## Making choice: Logic 

In the previous lesson we studied some data and noticed problems in them that we dealed by doing test and eliminated the one's with problems. To realise that we use the *if* statement. The general form is:

```python
if <test1>:         # first test
    <statements1>
elif <test2>:       # optional elif test
    <statements2>
else:
    <statements3>   # Optional else test
```

<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>

 <ol>
    <li> 
     Using the conditional structure: 
     ```if ...:  else:```
     For the numbers up to 10, print on screen whether the number is an odd or an even.
    </li>
Hint: Combine conditional and loop in this challenge.
    <br>
    <li>
    Write a conditional block which will print on screen when a number is null, a digit (1, ...9) or a number.
    </li>
    <br>
</div>

Python has an operator *%* which return the rest of the division between two numbers.

Usage: 

```python
a % b 
```

If a is divisible by b the result will be equal to zero if not that will be the rest of the division.

e.g: to determine if a number is an even you can write:

```python
a % 2 
```

If *a* is even the result will be zero. 

### Solution to Challenge 1

In [23]:
for i in range(0,11): 
    if i % 2:
        print(i, "is odd")
    else:
        print(i, "is even")

0 is even
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even


### Solution to Challenge 2

In [24]:
val = 0

if val>0 and val<10:
    print('Value: ', val, 'is a digit.')
elif val==0:
    print('Value', val, 'is zero')
else:
    print('Value: ', val, 'is a number.')

Value 0 is zero


# Functions

Function allowed the developer to write a sequence of commands one time and to reuse it when he need it. 

Breaking a software in small functions is considered as good practice and will help you a lot to maintain your software.

Function in python are starting with the keyword ```def``` follow by the name of the function, the parameters and by a block of commands.

```python

def func_name(arg1,arg2):
    <commands1>
    <commands2>
    return <something>
```

In [25]:
def greeting():
    print('Hello')

**note:**

Defining a function does not run it. You have to call it.

In [26]:
greeting()

Hello


Function can take arguments as input and do some operation on it:

In [27]:
def print_date(year, month, day):
    date = str(year) + '/' + str(month) + '/' + str(day)
    print(date)
    
print_date(2018, 2, 20)

2018/2/20


Function in python accept position and name calling. You can mixed both but the name calling argument have to be always **after** the positional ones.

Here an example where: argument year is called with the position (first) but the two others, non optional, argument are called by name.

In [28]:
print_date(2012, day=20, month=2)

2012/2/20


Function can **return** a result by using the keyword ```return```.

*return* exit the function. The commands after that (if executed) will not be run.

In [29]:
def average(values):
    l = len(values)
    if l != 0:
        return sum(values)/l

a_list = [1, 2, 3, 4]

a = average(a_list)
print('Average:', a)

Average: 2.5


Function can have optional argument:

In [30]:
def myname(name='Gruel', firstname='Nicolas'):
    print(firstname, name)

In [31]:
myname()

Nicolas Gruel


In [32]:
myname('Capes', firstname='Gerard')

Gerard Capes


<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>
<li>
    Write a function which will calculate the polynomial: $f(x) = 3x^2 + 8x + 4$
</li>
</div>


In [33]:
def f(x):
    return (3*x*x + 8*x + 4)

## Documenting your function

Python has a very powerful system to document function which automatically create a helper.

Here we are using the numpy documention format: [numpydoc](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)

In [34]:
def f(x):
    '''Function which return the value of the polynome: :math:`3x^2 + 8x + 4`

    Input
    -----
    
    x: float
        a number that will be the input value of the polynomial
    
    Return
    ------
    float
        return the value of the polynomial 
    '''
    return 3*x*x + 8*x + 4

In [35]:
help(f)

Help on function f in module __main__:

f(x)
    Function which return the value of the polynome: :math:`3x^2 + 8x + 4`
    
    Input
    -----
    
    x: float
        a number that will be the input value of the polynomial
    
    Return
    ------
    float
        return the value of the polynomial



In [36]:
f?

# Input/Output 

## Reading numerical data from a file

<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>

In the first lesson, we open a data file using a function provided by the *numpy* library.

   <li>Verify that you are in the expected working directory (data) and if not change your working directory. (use the console part of spyder to run the command learned in jupyter)
    </li>
   <li>
   Can you print on screen the files present in the current directory?
   </li>
   <li>Can you save in the variable *data01* the inflammation data from the file *inflammation-01.csv* (use ```numpy```).
   </li>
   <br>
</div>

### Jupyter/ipython:

In [37]:
pwd

'/home/gruel/Documents/Cours/Python advanced class - Jupyter notebook'

In [38]:
ls data

502nmos.fits  gapminder_gdp_europe.csv  inflammation-03.csv
agelist.txt   inflammation-01.csv       informations.txt
ex1.txt       inflammation-02.csv       numpyarray.txt


In [39]:
cd data

/home/gruel/Documents/Cours/Python advanced class - Jupyter notebook/data


Reinitialisation to be able to run the pure python part.

In [40]:
cd ..

/home/gruel/Documents/Cours/Python advanced class - Jupyter notebook


### Pure python

In [41]:
import os
os.getcwd()

'/home/gruel/Documents/Cours/Python advanced class - Jupyter notebook'

In [42]:
os.chdir('data')

In [43]:
os.getcwd()

'/home/gruel/Documents/Cours/Python advanced class - Jupyter notebook/data'

In [44]:
os.listdir()

['502nmos.fits',
 'numpyarray.txt',
 'inflammation-03.csv',
 'inflammation-01.csv',
 'agelist.txt',
 'inflammation-02.csv',
 'informations.txt',
 'gapminder_gdp_europe.csv',
 'ex1.txt']

In [45]:
import numpy
fname = 'inflammation-01.csv'
data01 = numpy.loadtxt(fname, delimiter=',')
print('data in file ', fname, ':\n', data01)
print('data type:', type(data01))

data in file  inflammation-01.csv :
 [[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
data type: <class 'numpy.ndarray'>


The *numpy* function *loadtxt* is very convenient but does have limitations and will not work or will work not as expected for other files even ascii file and we will see an example later.

Python is providing a more generic function *open* to interact with file. In general, when you are dealing with files this is done in four different steps: 

1. Open the file
2. Read the content of the file
3. Update/write in the file
4. Close the file.


## Reading a text file using python

In [46]:
fname = 'inflammation-01.csv'
f = open(fname, 'r')
data1 = f.readlines()
f.close()
print('Type of the data:', type(data1))

Type of the data: <class 'list'>


In [47]:
print('contents of the file:\n', data1[0:2])

contents of the file:
 ['0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0\n', '0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1\n']


If you just want to read the content of a file and put it in memory. It is better to use the following method to be sure that you do not forget to close the file. 

In [48]:
with open(fname,'r') as f:
    data2 = f.readlines()
print('Type of the data:', type(data2))

Type of the data: <class 'list'>


In [49]:
print('content of the file:\n', data2[0:2])

content of the file:
 ['0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0\n', '0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1\n']


We can verify that the variables *data1* and *data2* are the same (we are reading the same file)

In [50]:
data1 == data2

True

<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>
<li>
    Convert the variable <b>data1</b> from a list of strings to a numpy array.
</li>
Hint: to remove the character ```\n``` at the end of a string you can use the method ```strip()```. You can also use the method ```split(',')``` which will split the string related to the character ```,```
</div>

### Solution 1

In [51]:
data = data1.copy()
for i,line in enumerate(data):
    line = line.strip().split(',')
    for j in range(len(line)):
        line[j] = int(line[j])
    data[i] = line
print(data[0:2])

[[0, 0, 1, 3, 1, 2, 4, 7, 8, 3, 3, 3, 10, 5, 7, 4, 7, 7, 12, 18, 6, 13, 11, 11, 7, 7, 4, 6, 8, 8, 4, 4, 5, 7, 3, 4, 2, 3, 0, 0], [0, 1, 2, 1, 2, 1, 3, 2, 2, 6, 10, 11, 5, 9, 4, 4, 7, 16, 8, 6, 18, 4, 12, 5, 12, 7, 11, 5, 11, 3, 3, 5, 4, 4, 5, 5, 1, 1, 0, 1]]


### Solution 2

This second method is using a new tool call *list comprehension* which allow the developer to create a list without the for block and the append.

```python
new_list = [ expression(i) for i in oldlist if filter(i)]
```

The filter *if (condition)*  is optional.

In [52]:
data = data1.copy()
for i,line in enumerate(data):
    line = line.strip().split(',')
    data[i] = [int(j) for j in line]
print(data[0:2])

[[0, 0, 1, 3, 1, 2, 4, 7, 8, 3, 3, 3, 10, 5, 7, 4, 7, 7, 12, 18, 6, 13, 11, 11, 7, 7, 4, 6, 8, 8, 4, 4, 5, 7, 3, 4, 2, 3, 0, 0], [0, 1, 2, 1, 2, 1, 3, 2, 2, 6, 10, 11, 5, 9, 4, 4, 7, 16, 8, 6, 18, 4, 12, 5, 12, 7, 11, 5, 11, 3, 3, 5, 4, 4, 5, 5, 1, 1, 0, 1]]


And now we can convert it as a numpy array.

In [53]:
data = numpy.array(data)
print('Data:\n', data)
print('Data type:', type(data))

Data:
 [[0 0 1 ... 3 0 0]
 [0 1 2 ... 1 0 1]
 [0 1 1 ... 2 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 2 0]
 [0 0 1 ... 1 1 0]]
Data type: <class 'numpy.ndarray'>


As You can see that the numpy function is saving us a lot of line of code and since the number of bugs in a software is strongly correlated with the number of lines this is a very good things to remember. If you can use the tools provided by other people.

## Saving data in a file

We mention before that saving in file will be similar than to read. Here an example:

In [54]:
line = 'A line we want to save in a file'
line2 = 'Another line'

f = open('ex1.txt', 'w')
f.write(line)
f.write('\n')
f.write(line2)
f.close()

**Attention:**

you can save only string in a file. To save something else you have to convert it before or use method provided by a library.

<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>
<li>
    Try to save the variable data (a numpy array) in a file.
</li>
</div>

In [55]:
print('Data type:', type(data))
f = open('numpyarray.txt', 'w')
f.write(data)
f.close()

Data type: <class 'numpy.ndarray'>


TypeError: write() argument must be str, not numpy.ndarray

Numpy provides functions to achieve this. Here we want to save in a text file:

In [56]:
numpy.savetxt('numpyarray.txt', data)

## Complex data file

In [57]:
%more agelist.txt

<div style='background:#B1E0A8; padding:10px 10px 10px 10px;'>
<H2> Challenges </H2>
<li>
    Try to read the file <i>phonelist.txt</i> into a variable using <i>loadtxt</i> function.
</li>
<li>Use another method to read the file.
</li>
</div>

In [58]:
data = numpy.loadtxt('agelist.txt')

ValueError: could not convert string to float: 'Name'

In [59]:
with open('agelist.txt', 'r') as f:
    phonelist = f.readlines()

In [60]:
print(phonelist)

['Name    Age     \n', 'Bob     18\n', 'Jane    24\n', 'Alice   35\n']
